# Generated by Django 4.2.1 on 2023-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_timestamp_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
