# Generated by Django 4.2.1 on 2023-06-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lost',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
